### ISSUE TITLE
Bug report on documentation

### ISSUE THREAD

**Issue by StefanoOcchetti** [linuxforphp/filebrowser#2]
**Describe the bug**

A wrong documentation is provided in:

/[docs](https://github.com/linuxforphp/filebrowser/tree/master/docs)/installation.rst

In section **Install on fresh Ubuntu 18.04 or Debian 10.3**,  the download address specified in the wget command is incorrect.

    wget https://filebrowser.linuxforphp.com/files/filebrowser_latest.zip
    unzip filebrowser_latest.zip && rm filebrowser_latest.zip

The domain seems to be _.net_ (instead of _.com_) and no __latest_ file is available. 

**To Reproduce**
1. Go to '[...](https://filebrowser.readthedocs.io/en/latest/installation.html#install-on-fresh-ubuntu-18-04-or-debian-10-3)'
2. Follow the instructions
3. wget reports an error

**Expected behavior**
wget should correctly find the resource specified

**Environment (please complete the following information):**
 - FileBrowser Version [e.g. 8.0.2]

**Additional context**
I solved the problem by manually changing the resource address and name, pointing to rev 8.0.2 explicitly.

    wget https://filebrowser.linuxforphp.net/files/filebrowser-8.0.2.zip
    unzip filebrowser-8.0.2.zip && rm filebrowser-8.0.2.zip

 Though, no address seems to be available for a generic "latest" version package.

**Comment by andrewscaya** [comment]
Hello @StefanoOcchetti --

Many thanks for reporting this. We'll update the documentation within the next few hours.

Cheers!

**Comment by andrewscaya** [comment]
Fixed with e00c12fa5e9a71479d718b3037626c0881d0e9f4 (Release-8.1.0).

Thanks for reporting this, @StefanoOcchetti!

**Comment by andrewscaya** [comment]
I'll reopen this issue since ReadTheDocs is having an issue currently, and the new version of our documentation cannot be deployed.

**Comment by andrewscaya** [comment]
Sphinx requirements added to the 8.1.0 release.
