### ISSUE TITLE
How to set storage path?

### ISSUE THREAD

**Issue by stunzz** [linuxforphp/filebrowser#4]
Hey there, I have been using the file browser cloud successfully for the last 3 months on my Raspberry Pi. Now my SD Card is out of space. So, I plugged and mounted an external SSD and put my all data in it. But now I want to the file browser cloud to point to my data stored in the SSD the mount point is - `/mnt/Home_Drive`
Please guide me through it. I already read the documentation thoroughly but can't figure out how to set the storage path.

**Comment by andrewscaya** [comment]
Hi,

You can change the main configuration file (configuration_sample.php -> configuration.php). You only need to change the 'REPOSITORY_ROOT' constant, and set it to a different path.

Or, you can use a symlink or a hardlink to link another directory to the application's current path ('repository'). This second approach is maybe the best option in your case.

Many thanks for your interest in the LfPHP FileBrowser!
