### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by jamzam90** [linuxforphp/filebrowser#7]
How would I go about configuring the s3client to handle backblaze b2?

**Comment by andrewscaya** [comment]
Hi @jamzam90 ,

We don't currently support Backblaze, but if you develop a driver that is compatible with their API, we would certainly be interested in including it in the next release of the FileBrowser.

Many thanks in advance!

Best regards,

Andrew

**Comment by jamzam90** [comment]
I'm uncertain on where to start just due to being unfamiliar with php, both flysystem and backblazes docs indicate it is possible by configuring the s3client and then inserting it into the client portion of the adapter.

**Comment by andrewscaya** [comment]
Hi @jamzam90,

You would have to create a [PHP Flysystem adapter class](https://flysystem.thephpleague.com/docs/advanced/creating-an-adapter/), that implements the [FilesystemAdapter interface](https://github.com/thephpleague/flysystem/blob/3.x/src/FilesystemAdapter.php), and add the corresponding configuration key in the main 'configuration.php' file (['storage']['driver']['config']). FileBrowser will then use your new adapter class, whenever an interaction with the file repository is requested.

Example configuration for the S3 driver (['storage']['driver']['config']):

```
'driver' => [
    'config' => [
        'separator' => '/',
        'config' => [],
        'adapter' => function () {
            $client = new \Aws\S3\S3Client([
                'credentials' => [
                    'key' => '123456',
                    'secret' => 'secret123456',
                ],
                'region' => 'us-east-1',
                'version' => 'latest',
            ]);

            return new \League\Flysystem\AwsS3v3\AwsS3Adapter($client, 'my-bucket-name');
        },
    ],
],
```

Happy PHP'ing! :)
